language: minimal
services:
- docker
script:
- docker run -v "$TRAVIS_BUILD_DIR":/postfacto postfacto/dev:2.6.3-12.6.0 /bin/bash -c "cd /postfacto && npm config set user 0 && npm config set unsafe-perm true && ./deps.sh && EPHEMERAL_CONTAINER=true ./test.sh && ./package.sh"
deploy:
  provider: releases
  draft: true
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: s8oYFnWM5jrKsERW8+UfzaAEqVViQboy20Fg69vYVUW9EeHwHGcnAzMHIrCzJSLyHZ8/OE8inHPc0F29ud+XkqU8aqBhYvVoZnWsjYEl2flXrAwN+qiflZXKsoJYtLhjTYk1MIMH2wa75IJIOZ3Nsbrw6jqOqT996cyrxN4xc2U8mCWgenaQdMyRmnaw6zYdNvqFM0Gerw6JWWVyh2CtXmLEFk70qCzowtwlS2JoATz9l8Z2jmuoLL0AUmswnVJly146dZT55JiSxhmDRnqpj0OGVfLCkKp4me7GQD/RctPQ8DnOd93WjKaEkb7oDDRjX7yG5xOES+E30K8Q3DyRdJlQ6X2RvzqqHD4++mZ0k+MrgLaOtyka1gSZ8aLfzuvlddAFtPd2r/rYHs+55eg7Z7aRK+bswlqzI7Guf2Rq8Qcaj58/iF5VZwUlHA6j1HKTvhpshEDlG3R9EulBjZNQxYaFRzN5Ppnd7WbGk7vJDlja9F/LZfauWPP+5gRqynWSxXJCQSkjX8zvoYcbFjYasHGmQCmOE8TyRyUKRVf5TUCLDZiRiTfSjD5FB+DqXDrhPJygZEZaxKaw22Vze2/lqnT4a1U+0toXP8mFnPOdDEEdnpLWFJXXk4XDEW2NX07Gw1IwvLeFlJ9PueXN1Te1LGj4W0zhLsj/UmRDM0CoqtM=
  file: package.zip
  on:
    repo: textbook/postfacto
    branch: deploy-test
