#
# Postfacto, a free, open-source and self-hosted retro tool aimed at helping
# remote teams.
#
# Copyright (C) 2016 - Present Pivotal Software, Inc.
#
# This program is free software: you can redistribute it and/or modify
#
# it under the terms of the GNU Affero General Public License as
#
# published by the Free Software Foundation, either version 3 of the
#
# License, or (at your option) any later version.
#
#
#
# This program is distributed in the hope that it will be useful,
#
# but WITHOUT ANY WARRANTY; without even the implied warranty of
#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
# GNU Affero General Public License for more details.
#
#
#
# You should have received a copy of the GNU Affero General Public License
#
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
version: '3.7'

services:
  db:
    environment:
      - POSTGRES_USER=root
    image: postgres:11.4-alpine
  redis:
    image: redis:5.0.5-alpine
  rails:
    build:
      context: ../../.
      dockerfile: docker/release/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://db:5432
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
    image: postfacto/release:dev
    ports:
      - "4000:4000"
