name: Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          "$GITHUB_WORKSPACE/.npm_cache"
          "$GITHUB_WORKSPACE/.bundler_cache"
        key: postfacto-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          postfacto-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/Gemfile.lock') }}
          postfacto-${{ hashFiles('**/package-lock.json') }}-
          postfacto-
    - uses: docker/setup-buildx-action@v1
    - run: |
        docker run \
          -v "$GITHUB_WORKSPACE/.npm_cache":/npm_cache \
          -v "$GITHUB_WORKSPACE/.bundler_cache":/bundler_cache \
          -v "$GITHUB_WORKSPACE":/postfacto \
          -e npm_config_cache=/npm_cache \
          -e BUNDLE_PATH=/bundler_cache \
          postfacto/dev:2.7.3-14.16.1 \
          /bin/bash \
          -c "cd /postfacto && npm config set user 0 && npm config set unsafe-perm true && ./deps.sh && EPHEMERAL_CONTAINER=true ./test.sh"
