name: Pipeline

on: [push, pull_request]

jobs:
  ruby-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
        working-directory: api
    - run: bundle install --without production
      working-directory: api
    - run: bundle exec rake db:create db:migrate
      working-directory: api
    - run: bundle exec rake
      working-directory: api

  node-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.16.1'
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: postfacto-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          postfacto-npm-${{ hashFiles('**/package-lock.json') }}
          postfacto-npm-
    - run: npm ci
      working-directory: web
    - run: npm run lint
      working-directory: web
    - run: npm test
      working-directory: web

  e2e-test:
    runs-on: ubuntu-20.04
    needs:
    - ruby-test
    - node-test
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: e2e.sh
      run: |
        docker run \
          -v "$GITHUB_WORKSPACE":/postfacto \
          postfacto/dev:2.7.3-14.16.1 /bin/bash \
          -c "cd /postfacto && npm config set user 0 && npm config set unsafe-perm true && ./deps.sh && EPHEMERAL_CONTAINER=true ./e2e.sh"

  docker-build:
    runs-on: ubuntu-20.04
    needs: e2e-test
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Docker build
      run: |
        docker build \
          "$GITHUB_WORKSPACE" \
          -f "$GITHUB_WORKSPACE/Dockerfile" \
          -t travis-build-image

  package-build:
    runs-on: ubuntu-20.04
    needs: e2e-test
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Get full tag
      id: full_tag
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Helm build
      run: |
        docker run \
          -v "$GITHUB_WORKSPACE/deployment/helm/":/helm \
          -w /helm \
          --entrypoint /helm/build.sh \
          alpine/helm:3.2.1 $TAG
      env:
        TAG: ${{ steps.full_tag.outputs.VERSION }}
    - name: Package build
      run: |
        docker run \
          -v "$GITHUB_WORKSPACE":/postfacto \
          postfacto/dev:2.7.3-14.16.1 /bin/bash \
          -c "cd /postfacto && npm config set user 0 && npm config set unsafe-perm true && ./deps.sh && ./package.sh $TAG"
      env:
        TAG: ${{ steps.full_tag.outputs.VERSION }}

  smoke-build:
    runs-on: ubuntu-20.04
    needs: e2e-test
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Smoke build
      run: |
        docker build \
          "$GITHUB_WORKSPACE/smoke" \
          -f "$GITHUB_WORKSPACE/docker/smoke/Dockerfile" \
          -t travis-build-image-smoke
